### ISSUE TITLE
Edit parser test code for more flexible testing

### ISSUE THREAD

**Issue by amanda-chua** [AY2021S1-CS2113T-W12-2/tp#113]
For example the testing edit command parsed correctly, we can test any task number we want instead of just a fixed number.

**Comment by daniellimws** [comment]
Now we cannot do this because we are loading the `Task` attributes from the `TaskList` and filling them into the `EditCommand`. We can change `Task.edit` to instead check if the method arguments are `null`, and only modify the `Task` attributes if they are not `null`. By doing this, we can improve testability since `EditCommand` no longer needs to load the attributes from a `Task`.
